# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: city_mq_contract.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'city_mq_contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ity_mq_contract.proto\x12\x18\x63om.example.layout.proto\"\x83\x01\n\x11LayoutTaskMessage\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x01(\t\x12\x11\n\tlayoutDir\x18\x04 \x01(\t\x12\x14\n\x0cresponseMode\x18\x05 \x01(\t\x12\x17\n\x0f\x66orceRegenerate\x18\x06 \x01(\x08\"Z\n\x15LayoutProgressMessage\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"Z\n\x17LayoutTaskResultMessage\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06svgUrl\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"_\n\x10ModelTaskMessage\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\toutputDir\x18\x03 \x01(\t\x12\x1a\n\x12layoutJsonFilePath\x18\x04 \x01(\t\"Y\n\x14ModelProgressMessage\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\xd5\x01\n\x16ModelTaskResultMessage\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12V\n\x0bmodelsPaths\x18\x04 \x03(\x0b\x32\x41.com.example.layout.proto.ModelTaskResultMessage.ModelsPathsEntry\x1a\x32\n\x10ModelsPathsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'city_mq_contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELTASKRESULTMESSAGE_MODELSPATHSENTRY']._loaded_options = None
  _globals['_MODELTASKRESULTMESSAGE_MODELSPATHSENTRY']._serialized_options = b'8\001'
  _globals['_LAYOUTTASKMESSAGE']._serialized_start=53
  _globals['_LAYOUTTASKMESSAGE']._serialized_end=184
  _globals['_LAYOUTPROGRESSMESSAGE']._serialized_start=186
  _globals['_LAYOUTPROGRESSMESSAGE']._serialized_end=276
  _globals['_LAYOUTTASKRESULTMESSAGE']._serialized_start=278
  _globals['_LAYOUTTASKRESULTMESSAGE']._serialized_end=368
  _globals['_MODELTASKMESSAGE']._serialized_start=370
  _globals['_MODELTASKMESSAGE']._serialized_end=465
  _globals['_MODELPROGRESSMESSAGE']._serialized_start=467
  _globals['_MODELPROGRESSMESSAGE']._serialized_end=556
  _globals['_MODELTASKRESULTMESSAGE']._serialized_start=559
  _globals['_MODELTASKRESULTMESSAGE']._serialized_end=772
  _globals['_MODELTASKRESULTMESSAGE_MODELSPATHSENTRY']._serialized_start=722
  _globals['_MODELTASKRESULTMESSAGE_MODELSPATHSENTRY']._serialized_end=772
# @@protoc_insertion_point(module_scope)
